In [1]:
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import VotingClassifier

In [2]:
X = np.load("./tatanic_X_train.npy")
y = np.load("./tatanic_y_train.npy")

In [3]:
X[:5] # x features

array([[0.27345609, 0.01415106, 0.        , 1.        , 0.        ,
        0.125     , 0.        , 0.        , 0.        , 1.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        1.        , 0.        , 0.        , 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.473882  , 0.13913574, 0.        , 0.        , 1.        ,
        0.125     , 0.25      , 1.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 1.        , 0.        , 0.        , 0.        ,
        0.        , 1.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.32356257, 0.01546857, 0.        , 1.        , 1.        ,
        0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 0.        , 0.        , 1.    

In [4]:
y[:5]

array([0., 1., 1., 1., 0.])

In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [9]:
clflog = LogisticRegression(random_state=1)
clfdt = DecisionTreeClassifier(random_state=1)
clfgn = GaussianNB() #아직 안배운 것

models = [clflog, clfdt, clfgn]

for model in models:
    model.fit(x_train, y_train)
    pred = model.predict(x_test)
    score = model.score(x_test, y_test) #Returns the mean accuracy on the given test data and labels
#     print(model)
    print(score)
    print('-'*20)

0.8127340823970037
--------------------
0.7565543071161048
--------------------
0.45318352059925093
--------------------


C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [16]:

eclf_h = VotingClassifier(estimators=[('lr', clflog), ('rf', clfdt), ('gnb', clfgn)], voting='hard')
eclf_h.fit(x_train, y_train)
pred = eclf_h.predict(x_test)
score = eclf_h.score(x_test, y_test)
print(score)

0.7453183520599251


C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [13]:

eclf_s = VotingClassifier(estimators=[('lr', clflog), ('rf', clfdt), ('gnb', clfgn)], voting='soft') #voting을 'soft'라고 하면 확률
eclf_s.fit(x_train, y_train)
pred = eclf_s.predict(x_test)
from sklearn.metrics import classification_report
print(classification_report(y_test,pred))

score = eclf_s.score(x_test, y_test)
print(score)

              precision    recall  f1-score   support

         0.0       0.82      0.75      0.79       150
         1.0       0.72      0.79      0.75       117

   micro avg       0.77      0.77      0.77       267
   macro avg       0.77      0.77      0.77       267
weighted avg       0.78      0.77      0.77       267

0.7715355805243446


C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [11]:
clflog = LogisticRegression(random_state=1)
clfdt = DecisionTreeClassifier(random_state=1)
clfgn = GaussianNB()
eclf_h = VotingClassifier(estimators=[('lr', clflog), ('rf', clfdt), ('gnb', clfgn)], voting='hard')
eclf_s = VotingClassifier(estimators=[('lr', clflog), ('rf', clfdt), ('gnb', clfgn)], voting='soft')


In [12]:
models = [clflog, clfdt, clfgn, eclf_h, eclf_s]

In [26]:
for model in models:
    model.fit(x_train, y_train)
#    pred = model.predict(x_test)
#    여기서 x_test로 test해서 결과를 pred에 저장하고
#    from sklearn.metrics import classification_report 해서 
#    pred의 값과 y_test의 값과 비교한 결과를 classification_report로 뽑아내는데 그 과정을 한번에 끝내는 것이 .score이다.
#    classification에서 mean f1값을 뽑아내는 것이다.

    score = model.score(x_test, y_test)
#     print(model)
    print(score)
    print('-'*20)

0.8314606741573034
--------------------
0.7490636704119851
--------------------
0.37453183520599254
--------------------
0.7453183520599251
--------------------
0.7453183520599251
--------------------


C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [19]:
from sklearn.model_selection import cross_val_score
#cross_val_score는 교차검증을 반복하는 코드이다.
#test데이터의 수가 적었을 때, 모듈의 정확성을 판단할 때 더욱 정확하게 판단하기 위한 방법이다.

for model in models:
    scores = cross_val_score(model, x_train, y_train, cv=5)
    
    print(scores)
    print(scores.mean())
    print('-'*20)

[0.872      0.824      0.74193548 0.83064516 0.81451613]
0.8166193548387097
--------------------
[0.76       0.752      0.75806452 0.72580645 0.79032258]
0.7572387096774194
--------------------
[0.416      0.392      0.69354839 0.40322581 0.39516129]
0.4599870967741936
--------------------


C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this w

In [27]:
clf1 = LogisticRegression(random_state=1)
clf2 = DecisionTreeClassifier(random_state=1)
eclf1 = VotingClassifier(estimators=[('lr', clf1), ('dt', clf2)], voting='hard')
eclf2 = VotingClassifier(estimators=[('lr', clf1), ('dt', clf2)], voting='soft')
#hard voting: 단순 투표. 개별 모형의 결과 기준
#soft voting: 가중치 투표. 개별 모형의 조건부 확률의 합 기준

In [28]:
models = [clf1, clf2, eclf1, eclf2]

for model in models:
    scores = cross_val_score(model, x_train, y_train, cv=5)
    
    print(scores)
    print(scores.mean())
    print('-'*20)

[0.872      0.824      0.74193548 0.83064516 0.81451613]
0.8166193548387097
--------------------
[0.76       0.752      0.75806452 0.72580645 0.79032258]
0.7572387096774194
--------------------
[0.808      0.808      0.76612903 0.81451613 0.83064516]
0.8054580645161291
--------------------
[0.76       0.752      0.75806452 0.72580645 0.79032258]
0.7572387096774194
--------------------


C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this w

In [31]:
eclf = VotingClassifier(estimators=[('lr', clf1), ('dt', clf2)], voting='hard')

In [32]:
c_params = [0.1,  5.0, 7.0, 10.0, 15.0, 20.0, 100.0]

params ={
    "lr__solver" : ['liblinear'], "lr__penalty" : ["l2"], \
    "lr__C" : c_params, "dt__criterion" : ["gini", "entropy"],
    "dt__max_depth" : [10,8,7,6,5,4,3,2],
    "dt__min_samples_leaf": [1,2,3,4,5,6,7,8,9]
    }

In [33]:
# cross_validation(cv), grid_search(param_grid), ensemble(estimator) => 통합

from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(estimator=eclf, param_grid=params, cv=5)
grid = grid.fit(X, y)

In [34]:
grid.best_score_

0.84251968503937

In [35]:
grid.best_params_

{'dt__criterion': 'gini',
 'dt__max_depth': 10,
 'dt__min_samples_leaf': 5,
 'lr__C': 5.0,
 'lr__penalty': 'l2',
 'lr__solver': 'liblinear'}

In [36]:
c_params = [0.1, 5.0, 7.0, 10.0, 15.0, 20.0, 100.0]

params ={"solver" : ['liblinear'], "penalty" : ["l2"], "C" : c_params}
grid = GridSearchCV(clf1, param_grid=params, cv=5)
grid = grid.fit(X, y)

In [37]:
grid.best_score_

0.8267716535433071

In [38]:
grid.best_params_

{'C': 5.0, 'penalty': 'l2', 'solver': 'liblinear'}